# Generated by Django 5.2.1 on 2025-05-15 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato XX.XXX.XXX-Y o X.XXX.XXX-Y', max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(default='Chilena', max_length=50)),
                ('lateralidad', models.CharField(choices=[('zurdo', 'Zurdo'), ('diestro', 'Diestro'), ('ambidiestro', 'Ambidiestro')], max_length=20)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en Kilogramos', max_digits=5, null=True)),
                ('estatura_cm', models.IntegerField(blank=True, help_text='Estatura en centímetros', null=True)),
                ('prevision_salud', models.CharField(choices=[('fonasa', 'FONASA'), ('isapre', 'Isapre'), ('otra', 'Otra')], max_length=20)),
                ('numero_ficha', models.CharField(blank=True, help_text='Número de ficha único interno del club', max_length=20, null=True, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el jugador está actualmente activo en el club')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='gestion_clinica.division')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
