# Generated by Django 5.2.1 on 2025-05-15 05:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0002_jugador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionKinesica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_consulta', models.TextField()),
                ('prestaciones_realizadas', models.TextField()),
                ('estado_actual', models.TextField(help_text='Ej: En tratamiento, Alta médica, Derivado')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_kinesicas', to='gestion_clinica.jugador')),
                ('profesional_a_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atención Kinésica',
                'verbose_name_plural': 'Atenciones Kinésicas',
                'ordering': ['-fecha_atencion'],
            },
        ),
    ]
