# Generated by Django 5.2.1 on 2025-05-15 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0003_atencionkinesica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lesion', models.DateField()),
                ('diagnostico_medico', models.TextField()),
                ('tipo_lesion', models.CharField(blank=True, max_length=100)),
                ('region_cuerpo', models.CharField(blank=True, max_length=100)),
                ('mecanismo_lesional', models.CharField(blank=True, max_length=100)),
                ('condicion_lesion', models.CharField(blank=True, max_length=50)),
                ('etapa_deportiva_lesion', models.CharField(blank=True, max_length=50)),
                ('gravedad_lesion', models.CharField(blank=True, max_length=50)),
                ('dias_recuperacion_estimados', models.IntegerField(blank=True, null=True)),
                ('dias_recuperacion_reales', models.IntegerField(blank=True, null=True)),
                ('observaciones_lesion', models.TextField(blank=True, null=True)),
                ('partidos_ausente_estimados', models.IntegerField(blank=True, help_text='Ingreso manual por ahora', null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesiones', to='gestion_clinica.jugador')),
            ],
            options={
                'verbose_name': 'Lesión',
                'verbose_name_plural': 'Lesiones',
                'ordering': ['-fecha_lesion'],
            },
        ),
    ]
