# Generated by Django 5.2.1 on 2025-05-15 05:15

import django.db.models.deletion
import django.utils.timezone
import gestion_clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0004_lesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen (Radiografía, RMN, Eco)'), ('informe', 'Informe Médico'), ('otro', 'Otro Documento')], max_length=20)),
                ('titulo_descripcion', models.CharField(max_length=255)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.now)),
                ('archivo', models.FileField(upload_to=gestion_clinica.models.ruta_archivo_medico)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_medicos', to='gestion_clinica.jugador')),
            ],
            options={
                'verbose_name': 'Archivo Médico',
                'verbose_name_plural': 'Archivos Médicos',
                'ordering': ['-fecha_documento'],
            },
        ),
    ]
