# Generated by Django 5.2.1 on 2025-05-15 05:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0005_archivomedico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPostPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido_evaluado', models.DateField(default=django.utils.timezone.now)),
                ('rival', models.CharField(blank=True, help_text='Opcional: Rival del partido evaluado', max_length=100, null=True)),
                ('dolor_molestia', models.BooleanField(default=False, verbose_name='¿Sintió Dolor/Molestia?')),
                ('intensidad_dolor', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Aplicable si hay dolor/molestia', null=True)),
                ('zona_anatomica_dolor', models.CharField(blank=True, max_length=150, null=True)),
                ('mecanismo_dolor_evaluado', models.CharField(blank=True, choices=[('sobrecarga', 'Sobrecarga'), ('traumatismo', 'Traumatismo'), ('otro', 'Otro')], max_length=50, null=True)),
                ('diagnostico_presuntivo_postpartido', models.TextField(blank=True, null=True)),
                ('momento_aparicion_molestia', models.CharField(blank=True, help_text='Ej: Minuto 30, Post-partido', max_length=100, null=True)),
                ('tratamiento_inmediato_realizado', models.TextField(blank=True, null=True)),
                ('observaciones_checklist', models.TextField(blank=True, null=True)),
                ('fecha_registro_checklist', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_post_partido', to='gestion_clinica.jugador')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_completados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist Post-Partido',
                'verbose_name_plural': 'Checklists Post-Partido',
                'ordering': ['-fecha_partido_evaluado', '-fecha_registro_checklist'],
            },
        ),
    ]
