# Generated by Django 5.2.1 on 2025-05-15 05:40

import gestion_clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0006_checklistpostpartido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionkinesica',
            name='estado_actual',
            field=models.CharField(choices=[('tratamiento', 'En tratamiento'), ('alta', 'Alta médica'), ('derivado', 'Derivado a especialista'), ('control', 'Control periódico'), ('otro', 'Otro')], help_text='Estado actual del paciente', max_length=50),
        ),
        migrations.AlterField(
            model_name='checklistpostpartido',
            name='mecanismo_dolor_evaluado',
            field=models.CharField(blank=True, choices=[('sobrecarga', 'Sobrecarga'), ('traumatismo', 'Traumatismo'), ('contacto', 'Contacto con rival/compañero'), ('gesto_tecnico', 'Gesto técnico'), ('indeterminado', 'Indeterminado'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklistpostpartido',
            name='momento_aparicion_molestia',
            field=models.CharField(blank=True, choices=[('primer_tiempo', 'Primer tiempo'), ('segundo_tiempo', 'Segundo tiempo'), ('calentamiento', 'Calentamiento previo'), ('post_partido', 'Post-partido'), ('otro', 'Otro momento')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checklistpostpartido',
            name='zona_anatomica_dolor',
            field=models.CharField(blank=True, choices=[('tobillo_izq', 'Tobillo Izquierdo'), ('tobillo_der', 'Tobillo Derecho'), ('rodilla_izq', 'Rodilla Izquierda'), ('rodilla_der', 'Rodilla Derecha'), ('cadera_izq', 'Cadera Izquierda'), ('cadera_der', 'Cadera Derecha'), ('muslo_ant_izq', 'Muslo Anterior Izquierdo'), ('muslo_ant_der', 'Muslo Anterior Derecho'), ('muslo_post_izq', 'Muslo Posterior Izquierdo'), ('muslo_post_der', 'Muslo Posterior Derecho'), ('pantorrilla_izq', 'Pantorrilla Izquierda'), ('pantorrilla_der', 'Pantorrilla Derecha'), ('pie_izq', 'Pie Izquierdo'), ('pie_der', 'Pie Derecho'), ('hombro_izq', 'Hombro Izquierdo'), ('hombro_der', 'Hombro Derecho'), ('codo_izq', 'Codo Izquierdo'), ('codo_der', 'Codo Derecho'), ('muneca_izq', 'Muñeca Izquierda'), ('muneca_der', 'Muñeca Derecha'), ('mano_izq', 'Mano Izquierda'), ('mano_der', 'Mano Derecha'), ('columna_cervical', 'Columna Cervical'), ('columna_dorsal', 'Columna Dorsal'), ('columna_lumbar', 'Columna Lumbar'), ('abdomen', 'Abdomen'), ('pelvis', 'Pelvis'), ('cabeza', 'Cabeza'), ('facial', 'Región Facial'), ('otra', 'Otra Región')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='rut',
            field=models.CharField(help_text='Formato XX.XXX.XXX-Y o X.XXX.XXX-Y', max_length=12, unique=True, validators=[gestion_clinica.models.validar_rut_chileno]),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='condicion_lesion',
            field=models.CharField(choices=[('aguda', 'Aguda'), ('cronica', 'Crónica'), ('recidivante', 'Recidivante'), ('sobreaguda', 'Sobreaguda')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='etapa_deportiva_lesion',
            field=models.CharField(choices=[('pretemporada', 'Pretemporada'), ('competencia', 'Competencia'), ('posttemporada', 'Posttemporada'), ('entrenamiento', 'Entrenamiento'), ('partido', 'Partido oficial'), ('amistoso', 'Partido amistoso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='gravedad_lesion',
            field=models.CharField(choices=[('leve', 'Leve (1-7 días)'), ('moderada', 'Moderada (8-28 días)'), ('grave', 'Grave (> 28 días)'), ('severa', 'Severa (requiere cirugía)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='mecanismo_lesional',
            field=models.CharField(choices=[('contacto', 'Por contacto'), ('sin_contacto', 'Sin contacto'), ('sobrecarga', 'Sobrecarga'), ('traumatico', 'Traumático'), ('indirecto', 'Mecanismo indirecto'), ('otro', 'Otro mecanismo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='region_cuerpo',
            field=models.CharField(choices=[('tobillo_izq', 'Tobillo Izquierdo'), ('tobillo_der', 'Tobillo Derecho'), ('rodilla_izq', 'Rodilla Izquierda'), ('rodilla_der', 'Rodilla Derecha'), ('cadera_izq', 'Cadera Izquierda'), ('cadera_der', 'Cadera Derecha'), ('muslo_ant_izq', 'Muslo Anterior Izquierdo'), ('muslo_ant_der', 'Muslo Anterior Derecho'), ('muslo_post_izq', 'Muslo Posterior Izquierdo'), ('muslo_post_der', 'Muslo Posterior Derecho'), ('pantorrilla_izq', 'Pantorrilla Izquierda'), ('pantorrilla_der', 'Pantorrilla Derecha'), ('pie_izq', 'Pie Izquierdo'), ('pie_der', 'Pie Derecho'), ('hombro_izq', 'Hombro Izquierdo'), ('hombro_der', 'Hombro Derecho'), ('codo_izq', 'Codo Izquierdo'), ('codo_der', 'Codo Derecho'), ('muneca_izq', 'Muñeca Izquierda'), ('muneca_der', 'Muñeca Derecha'), ('mano_izq', 'Mano Izquierda'), ('mano_der', 'Mano Derecha'), ('columna_cervical', 'Columna Cervical'), ('columna_dorsal', 'Columna Dorsal'), ('columna_lumbar', 'Columna Lumbar'), ('abdomen', 'Abdomen'), ('pelvis', 'Pelvis'), ('cabeza', 'Cabeza'), ('facial', 'Región Facial'), ('otra', 'Otra Región')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='tipo_lesion',
            field=models.CharField(choices=[('muscular', 'Muscular'), ('ligamentosa', 'Ligamentosa'), ('osea', 'Ósea'), ('tendinosa', 'Tendinosa'), ('articular', 'Articular'), ('meniscal', 'Meniscal'), ('contusion', 'Contusión'), ('otra', 'Otra')], max_length=100),
        ),
    ]
