# Generated by Django 5.2.1 on 2025-05-15 05:50

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0007_alter_atencionkinesica_estado_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistpostpartido',
            name='intensidad_leve',
            field=models.BooleanField(default=False, verbose_name='Intensidad: Leve (1-2)'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='intensidad_moderada',
            field=models.BooleanField(default=False, verbose_name='Intensidad: Moderada (3-4)'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='intensidad_severa',
            field=models.BooleanField(default=False, verbose_name='Intensidad: Severa (5)'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='mecanismo_contacto',
            field=models.BooleanField(default=False, verbose_name='Mecanismo: Contacto con rival/compañero'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='mecanismo_gesto_tecnico',
            field=models.BooleanField(default=False, verbose_name='Mecanismo: Gesto técnico'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='mecanismo_indeterminado',
            field=models.BooleanField(default=False, verbose_name='Mecanismo: Indeterminado'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='mecanismo_sobrecarga',
            field=models.BooleanField(default=False, verbose_name='Mecanismo: Sobrecarga'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='mecanismo_traumatismo',
            field=models.BooleanField(default=False, verbose_name='Mecanismo: Traumatismo'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='momento_calentamiento',
            field=models.BooleanField(default=False, verbose_name='Momento: Calentamiento previo'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='momento_post_partido',
            field=models.BooleanField(default=False, verbose_name='Momento: Post-partido'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='momento_primer_tiempo',
            field=models.BooleanField(default=False, verbose_name='Momento: Primer tiempo'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='momento_segundo_tiempo',
            field=models.BooleanField(default=False, verbose_name='Momento: Segundo tiempo'),
        ),
        migrations.AddField(
            model_name='checklistpostpartido',
            name='zonas_anatomicas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tobillo_izq', 'Tobillo Izquierdo'), ('tobillo_der', 'Tobillo Derecho'), ('rodilla_izq', 'Rodilla Izquierda'), ('rodilla_der', 'Rodilla Derecha'), ('cadera_izq', 'Cadera Izquierda'), ('cadera_der', 'Cadera Derecha'), ('muslo_ant_izq', 'Muslo Anterior Izquierdo'), ('muslo_ant_der', 'Muslo Anterior Derecho'), ('muslo_post_izq', 'Muslo Posterior Izquierdo'), ('muslo_post_der', 'Muslo Posterior Derecho'), ('pantorrilla_izq', 'Pantorrilla Izquierda'), ('pantorrilla_der', 'Pantorrilla Derecha'), ('pie_izq', 'Pie Izquierdo'), ('pie_der', 'Pie Derecho'), ('hombro_izq', 'Hombro Izquierdo'), ('hombro_der', 'Hombro Derecho'), ('codo_izq', 'Codo Izquierdo'), ('codo_der', 'Codo Derecho'), ('muneca_izq', 'Muñeca Izquierda'), ('muneca_der', 'Muñeca Derecha'), ('mano_izq', 'Mano Izquierda'), ('mano_der', 'Mano Derecha'), ('columna_cervical', 'Columna Cervical'), ('columna_dorsal', 'Columna Dorsal'), ('columna_lumbar', 'Columna Lumbar'), ('abdomen', 'Abdomen'), ('pelvis', 'Pelvis'), ('cabeza', 'Cabeza'), ('facial', 'Región Facial'), ('otra', 'Otra Región')], help_text='Seleccione todas las zonas anatómicas donde se siente dolor o molestia', max_length=336, null=True, verbose_name='Zonas anatómicas con dolor'),
        ),
        migrations.AlterField(
            model_name='checklistpostpartido',
            name='intensidad_dolor',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Campo deprecado, usar los nuevos campos intensidad_*', null=True),
        ),
        migrations.AlterField(
            model_name='checklistpostpartido',
            name='mecanismo_dolor_evaluado',
            field=models.CharField(blank=True, choices=[('sobrecarga', 'Sobrecarga'), ('traumatismo', 'Traumatismo'), ('contacto', 'Contacto con rival/compañero'), ('gesto_tecnico', 'Gesto técnico'), ('indeterminado', 'Indeterminado'), ('otro', 'Otro')], help_text='Campo deprecado, usar los nuevos campos mecanismo_*', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklistpostpartido',
            name='momento_aparicion_molestia',
            field=models.CharField(blank=True, choices=[('primer_tiempo', 'Primer tiempo'), ('segundo_tiempo', 'Segundo tiempo'), ('calentamiento', 'Calentamiento previo'), ('post_partido', 'Post-partido'), ('otro', 'Otro momento')], help_text='Campo deprecado, usar los nuevos campos momento_*', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checklistpostpartido',
            name='zona_anatomica_dolor',
            field=models.CharField(blank=True, choices=[('tobillo_izq', 'Tobillo Izquierdo'), ('tobillo_der', 'Tobillo Derecho'), ('rodilla_izq', 'Rodilla Izquierda'), ('rodilla_der', 'Rodilla Derecha'), ('cadera_izq', 'Cadera Izquierda'), ('cadera_der', 'Cadera Derecha'), ('muslo_ant_izq', 'Muslo Anterior Izquierdo'), ('muslo_ant_der', 'Muslo Anterior Derecho'), ('muslo_post_izq', 'Muslo Posterior Izquierdo'), ('muslo_post_der', 'Muslo Posterior Derecho'), ('pantorrilla_izq', 'Pantorrilla Izquierda'), ('pantorrilla_der', 'Pantorrilla Derecha'), ('pie_izq', 'Pie Izquierdo'), ('pie_der', 'Pie Derecho'), ('hombro_izq', 'Hombro Izquierdo'), ('hombro_der', 'Hombro Derecho'), ('codo_izq', 'Codo Izquierdo'), ('codo_der', 'Codo Derecho'), ('muneca_izq', 'Muñeca Izquierda'), ('muneca_der', 'Muñeca Derecha'), ('mano_izq', 'Mano Izquierda'), ('mano_der', 'Mano Derecha'), ('columna_cervical', 'Columna Cervical'), ('columna_dorsal', 'Columna Dorsal'), ('columna_lumbar', 'Columna Lumbar'), ('abdomen', 'Abdomen'), ('pelvis', 'Pelvis'), ('cabeza', 'Cabeza'), ('facial', 'Región Facial'), ('otra', 'Otra Región')], help_text='Campo deprecado, usar el nuevo campo zonas_anatomicas', max_length=150, null=True),
        ),
    ]
