# Generated by Django 5.2.1 on 2025-05-16 01:41

import gestion_clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0009_remove_checklistpostpartido_intensidad_leve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=gestion_clinica.models.ruta_foto_perfil_jugador, verbose_name='Foto de Perfil'),
        ),
    ]
