# Generated by Django 5.2.1 on 2025-05-29 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0010_jugador_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesion',
            name='esta_activa',
            field=models.BooleanField(default=True, help_text='Indica si la lesión está actualmente activa'),
        ),
        migrations.AddField(
            model_name='lesion',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha en que se da por finalizada la lesión', null=True),
        ),
        migrations.CreateModel(
            name='EstadoDiarioLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('camilla', 'Tratamiento en Camilla'), ('gimnasio', 'Tratamiento en Gimnasio'), ('reintegro', 'Reintegro Deportivo')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_diario', to='gestion_clinica.lesion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado Diario de Lesión',
                'verbose_name_plural': 'Estados Diarios de Lesiones',
                'ordering': ['-fecha'],
                'unique_together': {('lesion', 'fecha')},
            },
        ),
    ]
