# Generated by Django 5.2.1 on 2025-05-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0011_lesion_esta_activa_lesion_fecha_fin_and_more'),
    ]

    operations = [
    ]
