# Generated by Django 5.2.1 on 2025-06-10 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0013_alter_checklistpostpartido_options_partido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistpostpartido',
            name='partido',
            field=models.ForeignKey(help_text='Partido al que corresponde este checklist', on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='gestion_clinica.partido'),
        ),
    ]
