# Generated by Django 5.2.1 on 2025-06-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0014_alter_checklistpostpartido_partido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistpostpartido',
            name='intensidad_dolor',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True),
        ),
    ]
