# Generated by Django 5.2.1 on 2025-06-27 00:55

import django.db.models.deletion
import gestion_clinica.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0015_update_intensidad_dolor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT del usuario en formato XX.XXX.XXX-Y', max_length=12, unique=True, validators=[gestion_clinica.models.validar_rut_chileno])),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo', models.CharField(blank=True, help_text='Cargo o función en el club', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Usuario activo en el sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
